// Mocks generated by Mockito 5.0.16 from annotations
// in aoeiv_leaderboard/test/unit/cubit/rating_history_data_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:aoeiv_leaderboard/models/rating.dart' as _i4;
import 'package:aoeiv_leaderboard/repositories/rating_history_data_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [RatingHistoryDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRatingHistoryDataRepository extends _i1.Mock
    implements _i2.RatingHistoryDataRepository {
  MockRatingHistoryDataRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Rating>> fetchRatingHistoryData(
          int? leaderboardId, int? profileId) =>
      (super.noSuchMethod(
              Invocation.method(
                  #fetchRatingHistoryData, [leaderboardId, profileId]),
              returnValue: Future<List<_i4.Rating>>.value(<_i4.Rating>[]))
          as _i3.Future<List<_i4.Rating>>);
  @override
  String toString() => super.toString();
}
